# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_auto_20170605_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
